Scotch.create(name: "Lagavulin 16", price: "84")
Scotch.create(name: "Laphroaig 10 Year Old 'Cask Strength' Islay Single Malt", price: "55")
Scotch.create(name: "Ardbeg Uigeadail", price: "79")
Scotch.create(name: "Laphroaig 10 Year Old Single Malt ", price: "43")
Scotch.create(name: "Glenlivet 18 Year Old Single Malt ", price: "85")
Scotch.create(name: "Balvenie 15 Year Old Single Barrel Single Malt", price: "55")
Scotch.create(name: "Talisker 1992 Distillers Edition", price: "65")
Scotch.create(name: "Johnnie Walker Gold Label Blended", price: "70")
Scotch.create(name: "Laphroaig Quarter Cask Single Malt", price: "47")
Scotch.create(name: "Ardbeg Single Malt Scotch Corryvreckan", price: "90")
Scotch.create(name: "Tomatin 18 Year Old Single Malt ", price: "80")
Scotch.create(name: "Glenlivet Nadurra 16 Year Old Cask Strength Single Malt", price: "64")
Scotch.create(name: "Old Pulteney 17 Year Old Single Malt", price: "79")
Scotch.create(name: "Dalmore 12 Year Old Single Malt", price: "67")
Scotch.create(name: "Talisker 10 Year Old Single Malt ", price: "53")
Scotch.create(name: "Johnnie Walker Green Label Scotch", price: "66")
Scotch.create(name: "Aberlour 16 Year Old Single Malt ", price: "65")
Scotch.create(name: "Aberlour Single Malt Scotch, A'bunadh", price: "70")
Scotch.create(name: "Dalmore 15 Year Old Single Malt", price: "76")
Scotch.create(name: "Glenmorangie Quinta Ruban 12 Year Old Single Malt", price: "64")
